# Generated by Django 5.1.1 on 2025-01-22 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('codzienne_wydatki', 'Codzienne wydatki'), ('darowizna', 'Darowizna'), ('edukacja', 'Edukacja'), ('jedzenie_poza_domem', 'Jedzenie poza domem'), ('osobiste', 'Osobiste'), ('platnosci', 'Płatności'), ('praca', 'Praca'), ('rachunki', 'Rachunki'), ('rozrywka', 'Rozrywka'), ('transport', 'Transport'), ('uslugi', 'Usługi'), ('zakupy_spozywcze', 'Zakupy spożywcze')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CelOszczednosciowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('kwota_docelowa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obecna_kwota', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_osiagniecia', models.DateField(blank=True, null=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miesiac', models.CharField(choices=[('01', 'Styczeń'), ('02', 'Luty'), ('03', 'Marzec'), ('04', 'Kwiecień'), ('05', 'Maj'), ('06', 'Czerwiec'), ('07', 'Lipiec'), ('08', 'Sierpień'), ('09', 'Wrzesień'), ('10', 'Październik'), ('11', 'Listopad'), ('12', 'Grudzień')], max_length=2)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('przeczytane', models.BooleanField(default=False)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_budzetu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transakcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Przychód', 'Przychód'), ('Wydatek', 'Wydatek')], max_length=10)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('opis', models.TextField(blank=True, null=True)),
                ('kategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.kategoria')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
